(setq jabber-alert-info-message-hooks (quote (jabber-info-awesome jabber-info-echo jabber-info-display)))
(setq jabber-alert-message-hooks (quote (jabber-message-awesome jabber-message-echo jabber-message-scroll)))
(setq jabber-auto-reconnect t)
(setq jabber-chat-buffer-show-avatar nil)
(setq jabber-roster-show-bindings nil)
(setq jabber-roster-show-title nil)
(setq jabber-show-offline-contacts nil)
(setq jabber-vcard-avatars-retrieve nil)

(setq jabber-account-list (quote (("tortuxm@baobob.org" (:network-server . "xmpp1.hosted.im")))))
(setq jabber-vcard-avatars-retrieve nil)
